// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBNNQQxsJBFNOut3p-Mi23-ME3dElCPEB0',
    appId: '1:737649709599:web:e6fb0adfdcfcadc1c53b2a',
    messagingSenderId: '737649709599',
    projectId: 'zerospoils-23dae',
    authDomain: 'zerospoils-23dae.firebaseapp.com',
    storageBucket: 'zerospoils-23dae.firebasestorage.app',
    measurementId: 'G-B19X0G4D7C',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB9gkFgnewTsv8w6yLrAsvoPwjRgJhcMqE',
    appId: '1:737649709599:android:32573e486e4091f5c53b2a',
    messagingSenderId: '737649709599',
    projectId: 'zerospoils-23dae',
    storageBucket: 'zerospoils-23dae.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAiSItVLWhoIrrundahsDbWwA47_DAqWFw',
    appId: '1:737649709599:ios:1e4cf9f41d58c0c9c53b2a',
    messagingSenderId: '737649709599',
    projectId: 'zerospoils-23dae',
    storageBucket: 'zerospoils-23dae.firebasestorage.app',
    androidClientId:
        '737649709599-r5kbsgkcj5d8srbdrbijfcu636j8bma3.apps.googleusercontent.com',
    iosClientId:
        '737649709599-ervqrvbm4fpfhc4qd9inktjo5nqfav41.apps.googleusercontent.com',
    iosBundleId: 'com.zerospoils.zerospoils',
  );
}
