arb-dir: lib/l10n
template-arb-file: app_en.arb
output-localization-file: app_localizations.dart
output-class: AppLocalizations
output-dir: lib/generated_l10n
output-dir-history: macos/Flutter/ephemeral/Flutter/Generated
output-file: app_localizations.dart
no-synthetic-package: true
preferred-supported-locales:
  - en
  - fr_CA
use-deferred-loading: false
