#!/usr/bin/env python3
"""
Generate Dart constants from telemetry schemas.

Output: lib/telemetry/generated/telemetry_events.dart

Usage:
  python generate_dart_constants.py
"""

import json
from pathlib import Path
from datetime import datetime

SCHEMAS_DIR = Path(__file__).parent.parent / "schemas"
OUTPUT_FILE = Path(__file__).parent.parent.parent / "app" / "lib" / "telemetry" / "generated" / "telemetry_events.dart"

def generate_dart_file() -> str:
    """Generate Dart constants for telemetry events."""
    # Load allowlist
    with open(SCHEMAS_DIR / "allowlist.json") as f:
        allowlist = json.load(f)

    dart_code = f'''// Generated by generate_dart_constants.py on {datetime.now().isoformat()}
// DO NOT EDIT: Regenerate this file when schemas change

/// Telemetry event names (canonical identifiers)
abstract class TelemetryEvents {{
'''

    events = allowlist.get("events", {})
    for event_name in sorted(events.keys()):
        const_name = event_name.upper()
        dart_code += f"  static const String {const_name} = '{event_name}';\n"

    dart_code += """\n}

/// Event property constants (for type-safe event property names)
abstract class TelemetryProperties {
"""

    # Collect all properties across events
    all_props = set()
    for event_data in events.values():
        all_props.update(event_data.get("allowed_properties", []))

    for prop_name in sorted(all_props):
        const_name = prop_name.upper()
        dart_code += f"  static const String {const_name} = '{prop_name}';\n"

    dart_code += """}

/// Event schemas (event_name -> allowed properties)
abstract class TelemetrySchemas {
  static const Map<String, List<String>> eventProperties = {
"""

    for event_name in sorted(events.keys()):
        props = events[event_name].get("allowed_properties", [])
        props_str = ', '.join(f"'{p}'" for p in sorted(props))
        dart_code += f"    '{event_name}': [{props_str}],\n"

    dart_code += """  };
}
"""

    return dart_code

def main():
    output = generate_dart_file()
    
    # Create parent directories if needed
    OUTPUT_FILE.parent.mkdir(parents=True, exist_ok=True)
    
    with open(OUTPUT_FILE, "w") as f:
        f.write(output)
    
    print(f"✅ Generated {OUTPUT_FILE}")

if __name__ == "__main__":
    main()
